package snapshot

import (
	"bytes"
	"encoding/hex"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"websec/internal/validation"
)

// Every known-vector constant below was generated by the Python twin
// (web3sec-final src/webv2/snapshot.py) over the exact same tree, so a
// regression against the reference hashing is a hard fail.

// buildTree lays down the reference tree:
//
//	a.txt                     "hello"
//	sub/b.bin                 bytes(range(250))
//	sub/snapshot.json         '{"nested": true}'   (nested: included)
//	snapshot.json             '{"pin": true}'      (root: skipped)
//	cache/junk/x.txt          "x"                  (SOURCE_EXCLUDES: skipped)
//	z<0x01>weird name         ""                   (empty, control-char name)
func buildTree(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	mustWrite := func(rel, content string) {
		p := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	mustWrite("a.txt", "hello")
	mustWrite("sub/snapshot.json", `{"nested": true}`) // also creates sub/
	bin := make([]byte, 250)                           // bytes(range(250))
	for i := range bin {
		bin[i] = byte(i)
	}
	if err := os.WriteFile(filepath.Join(root, "sub", "b.bin"), bin, 0o644); err != nil {
		t.Fatal(err)
	}
	mustWrite("snapshot.json", `{"pin": true}`)
	mustWrite("cache/junk/x.txt", "x")
	if err := os.WriteFile(filepath.Join(root, "z\x01weird name"), nil, 0o644); err != nil {
		t.Fatal(err)
	}
	return root
}

func TestContentHashKnownVector(t *testing.T) {
	root := buildTree(t)
	h, n, err := ContentHash(root)
	if err != nil {
		t.Fatal(err)
	}
	if h != "1a93074d7ae40f557b2a461f7a3997ed0401196677d8c77cba3a52a2125e621a" {
		t.Errorf("contentHash: %s", h)
	}
	if n != 4 {
		t.Errorf("count: %d (root snapshot.json + cache/ must be excluded)", n)
	}
}

// The length prefixes make the digest path/content-unambiguous: a rename
// changes the hash even though the content (and here even the length
// class) is the same.
func TestContentHashRenameChangesHash(t *testing.T) {
	root := buildTree(t)
	if err := os.Rename(filepath.Join(root, "a.txt"), filepath.Join(root, "ab.txt")); err != nil {
		t.Fatal(err)
	}
	h, n, err := ContentHash(root)
	if err != nil {
		t.Fatal(err)
	}
	if h != "4fb1240ae9e869f9bac8712938a78c840ea4221dfcac240c3a4085aa7b77b2f4" {
		t.Errorf("renamed: %s", h)
	}
	if n != 4 {
		t.Errorf("count after rename: %d", n)
	}
}

func TestContentHashNewFile(t *testing.T) {
	root := buildTree(t)
	h0, n0, err := ContentHash(root)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "new.txt"), []byte("n"), 0o644); err != nil {
		t.Fatal(err)
	}
	h1, n1, err := ContentHash(root)
	if err != nil {
		t.Fatal(err)
	}
	if h1 == h0 {
		t.Error("adding a file must change the hash")
	}
	if n1 != n0+1 {
		t.Errorf("count: %d -> %d", n0, n1)
	}
}

// Python sorts Path objects by their PARTS tuple, not the joined string:
// for "a/b" vs "a-b", parts order puts a/b first while string order would
// put a-b first ("- " sorts before "/"). The hash must follow parts order.
func TestContentHashPartsOrder(t *testing.T) {
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "a"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "a-b"), []byte("one"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "a", "b"), []byte("two"), 0o644); err != nil {
		t.Fatal(err)
	}
	h, n, err := ContentHash(root)
	if err != nil {
		t.Fatal(err)
	}
	if h != "b2324dc5c06f6856fd937538f9f87d5ce67f362b28b1148595651504a1396755" {
		t.Errorf("parts order: %s", h)
	}
	if n != 2 {
		t.Errorf("count: %d", n)
	}
}

func TestPinnedFiles(t *testing.T) {
	root := buildTree(t)
	files, err := PinnedFiles(root)
	if err != nil {
		t.Fatal(err)
	}
	want := []string{"a.txt", "sub/b.bin", "sub/snapshot.json", "z\x01weird name"}
	if !reflect.DeepEqual(files, want) {
		t.Errorf("pinned: %q", files)
	}
}

func TestFileLeafKnownVectors(t *testing.T) {
	root := buildTree(t)
	leaf, err := FileLeaf(filepath.Join(root, "a.txt"), root)
	if err != nil {
		t.Fatal(err)
	}
	if hex.EncodeToString(leaf) !=
		"2659b57fca1b0e46c034da5c222d38f171818ba9ae0e7df9f25b875574c1362d" {
		t.Errorf("leaf a.txt: %x", leaf)
	}
	leaf, err = FileLeaf(filepath.Join(root, "sub", "b.bin"), root)
	if err != nil {
		t.Fatal(err)
	}
	if hex.EncodeToString(leaf) !=
		"f0f5b80d2fc29178c33705b1dee5b7918dd142497e0603f5c7c8f021ec766cc4" {
		t.Errorf("leaf b.bin: %x", leaf)
	}
}

// The framing (8-byte big-endian length before the path AND before the
// content) is what kills the aliasing a bare NUL framing allows: the
// split ("x", "ab") vs ("xa", "") must hash to different leaves.
func TestFileLeafFraming(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "x"), []byte("ab"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "xa"), nil, 0o644); err != nil {
		t.Fatal(err)
	}
	l1, _ := FileLeaf(filepath.Join(root, "x"), root)
	l2, _ := FileLeaf(filepath.Join(root, "xa"), root)
	if bytes.Equal(l1, l2) {
		t.Error("length prefixes must separate the two splits")
	}
}

func TestMerkleVectors(t *testing.T) {
	if got := MerkleRoot(nil); got !=
		"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" {
		t.Errorf("empty: %s", got)
	}
	// a single leaf is the root itself (the loop never runs) — the 32
	// digest bytes hex-encoded, no extra hashing round.
	leafA, _ := hex.DecodeString(
		"2659b57fca1b0e46c034da5c222d38f171818ba9ae0e7df9f25b875574c1362d")
	if got := MerkleRoot([][]byte{leafA}); got != hex.EncodeToString(leafA) {
		t.Errorf("single: %s", got)
	}
	// odd level: the last node is duplicated before pairing — so
	// (x,y,z) and (x,y,z,z) must land on the SAME root (vector from the
	// Python twin over the raw bytes).
	odd := MerkleRoot([][]byte{[]byte("x"), []byte("y"), []byte("z")})
	if odd != "f0c9f9bd58a2a928a04114d9cbd12c3cad8d19c591dd5b4be00c17b046a2319f" {
		t.Errorf("odd3: %s", odd)
	}
	if got := MerkleRoot([][]byte{[]byte("x"), []byte("y"), []byte("z"), []byte("z")}); got != odd {
		t.Errorf("odd-duplication: %s != %s", got, odd)
	}
}

func TestSourceMerkleRoot(t *testing.T) {
	root := buildTree(t)
	got, err := SourceMerkleRoot(root)
	if err != nil {
		t.Fatal(err)
	}
	if got != "de4d7ed6db532e64e7f884b0af09cbafeac7f9885358505b84874a6ed7c7bb06" {
		t.Errorf("source merkle: %s", got)
	}
}

func TestLockfileLeaves(t *testing.T) {
	root := t.TempDir()
	mustWrite := func(rel, content string) {
		if err := os.WriteFile(filepath.Join(root, rel), []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	mustWrite("package-lock.json", "{}")
	mustWrite("go.sum", "mod v1.0.0 h1:abc\n")
	mustWrite("notes.txt", "not a lockfile")
	leaves, err := LockfileLeaves(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(leaves) != 2 {
		t.Fatalf("lockfiles: %d leaves", len(leaves))
	}
	// pinned order: go.sum before package-lock.json.
	l1, _ := FileLeaf(filepath.Join(root, "go.sum"), root)
	if !bytes.Equal(leaves[0], l1) {
		t.Error("first lockfile leaf must be go.sum (pinned order)")
	}
}

func TestCanonicalMatchesCompact(t *testing.T) {
	v := validation.VObj(
		validation.KV{K: "z", V: validation.VStr("1")},
		validation.KV{K: "a", V: validation.VArr(validation.VInt(1), validation.VObj(
			validation.KV{K: "b", V: validation.VBool(true)},
		))},
	)
	if got, want := Canonical(v), validation.CanonCompact(v); got != want {
		t.Errorf("canonical: %s != %s", got, want)
	}
	if got := Canonical(v); got != `{"a":[1,{"b":true}],"z":"1"}` {
		t.Errorf("canonical: %s", got)
	}
}

// TestSymlinksHashAsThemselves pins r14 issue 5: the ported walk
// followed links, so a pin's "immutable" hash depended on bytes outside
// the campaign — editing an outside target made audit LIE ("the pinned
// copy was modified" when zero bytes of it moved), and anyone with
// write access to a target could permanently red any pin. Links now
// hash (and merkle) as their own target string, symmetric between
// source and staged copy; outside edits are inert, copy edits fire.
func TestSymlinksHashAsThemselves(t *testing.T) {
	root := t.TempDir()
	tree := filepath.Join(root, "tree")
	if err := os.MkdirAll(tree, 0o755); err != nil {
		t.Fatal(err)
	}
	outside := filepath.Join(root, "outside.sol")
	if err := os.WriteFile(outside, []byte("contract S {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(tree, "a.sol"),
		[]byte("contract A {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(outside, filepath.Join(tree, "link.sol")); err != nil {
		t.Fatal(err)
	}
	h1, n1, err := ContentHash(tree)
	if err != nil {
		t.Fatal(err)
	}
	if n1 != 2 {
		t.Fatalf("pinned %d files, want 2 (link counts as one)", n1)
	}
	m1, err := SourceMerkleRoot(tree)
	if err != nil {
		t.Fatal(err)
	}
	// Mutate the OUTSIDE target: nothing the campaign custodies moved.
	if err := os.WriteFile(outside, []byte("contract MUTATED{}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	h2, _, err := ContentHash(tree)
	if err != nil {
		t.Fatal(err)
	}
	m2, err := SourceMerkleRoot(tree)
	if err != nil {
		t.Fatal(err)
	}
	if h1 != h2 || m1 != m2 {
		t.Fatalf("outside bytes leaked into the pin's identity: %s/%s vs %s/%s",
			h1[:8], m1[:8], h2[:8], m2[:8])
	}
	// The STAGED copy (stageTree preserves links as links) hashes
	// IDENTICAL to the source — the audit's equality is between the two
	// trees the campaign owns.
	st, err := stageTree(tree, "", nil)
	if err != nil {
		t.Fatal(err)
	}
	defer discardStaged(st)
	h3, _, err := ContentHash(st.staging)
	if err != nil {
		t.Fatal(err)
	}
	if h3 != h1 {
		t.Fatalf("source and staged copy disagree: %s vs %s", h1[:8], h3[:8])
	}
	// A real change INSIDE custody (link removed from the copy) must
	// move the hash.
	if err := os.Remove(filepath.Join(st.staging, "link.sol")); err != nil {
		t.Fatal(err)
	}
	h4, _, err := ContentHash(st.staging)
	if err != nil {
		t.Fatal(err)
	}
	if h4 == h1 {
		t.Fatal("deleting the link from the copy left the hash unmoved")
	}
}
