package taxonomy

import (
	"encoding/json"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"websec/internal/findings"
	"websec/internal/validation"
)

// ---- fixtures ------------------------------------------------------------

// ptr is a string pointer for the *string API (nil == Python None).
func ptr(s string) *string { return &s }

// useConfig points ConfigDir at the committed config snapshot and restores it
// afterwards (the twin of monkeypatch.setattr(TX, "CONFIG_DIR", ...)).
func useConfig(t *testing.T, dir string) {
	t.Helper()
	oldRoot, oldDir := RepoRoot, ConfigDir
	t.Cleanup(func() { RepoRoot, ConfigDir = oldRoot, oldDir })
	SetConfigDir(dir)
}

// tmpConfig is _tmp_config: a per-test copy of the shipped config dir, so a
// test can add or modify map files without touching the real ones.
func tmpConfig(t *testing.T) string {
	t.Helper()
	dst := filepath.Join(t.TempDir(), "config")
	copyTree(t, filepath.Join("testdata", "config"), dst)
	useConfig(t, filepath.Dir(dst))
	return dst
}

// copyTree copies a small directory tree (config files, test fixtures).
func copyTree(t *testing.T, src, dst string) {
	t.Helper()
	entries, err := os.ReadDir(src)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		if e.IsDir() {
			copyTree(t, filepath.Join(src, e.Name()), filepath.Join(dst, e.Name()))
			continue
		}
		raw, err := os.ReadFile(filepath.Join(src, e.Name()))
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dst, e.Name()), raw, 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

// loadVectors decodes a committed vector table (generated by the Python twin).
func loadVectors(t *testing.T, name string, out any) {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "vectors", name))
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(raw, out); err != nil {
		t.Fatal(err)
	}
}

// equalStrings is the ordered list comparison.
func equalStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// ---- tests/test_taxonomy.py ----------------------------------------------

func TestKnownClassesIsCompleteAndStable(t *testing.T) {
	known := KnownClasses()
	for _, cls := range []string{"reentrancy", "access-control",
		"oracle-manipulation", "bridge-message", "cross-chain-replay",
		"economic-invariant", "liquidation-logic"} {
		if _, ok := known[cls]; !ok {
			t.Errorf("known_classes is missing %q", cls)
		}
	}
	// every class in the floor table is known (no class can be in the table
	// but missing from the taxonomy)
	for cls := range findings.CLASS_CONFIRM_FLOOR {
		if _, ok := known[cls]; !ok {
			t.Errorf("floor-table class %q is not in known_classes", cls)
		}
	}
}

func TestClassReportForKnown(t *testing.T) {
	r := ClassReport(ptr("reentrancy"))
	if !objAt(r, "known").B {
		t.Error("reentrancy report known = false, want true")
	}
	if got := objStr(r, "floor"); got != "E4" {
		t.Errorf("reentrancy report floor = %q, want E4", got)
	}
}

func TestClassReportForUnknownSuggestsMatches(t *testing.T) {
	r := ClassReport(ptr("reentrancyy")) // typo
	if objAt(r, "known").B {
		t.Error("reentrancyy report known = true, want false")
	}
	found := false
	for _, s := range objAt(r, "suggestions").A {
		if s.S == "reentrancy" {
			found = true
		}
	}
	if !found {
		t.Errorf("suggestions = %v, want reentrancy among them",
			validation.CanonCompact(objAt(r, "suggestions")))
	}
}

func TestClassAdvisoryUnknownNamesConservativeFloor(t *testing.T) {
	a := ClassAdvisory(ptr("quantum-decoherence"))
	for _, want := range []string{"unknown class", "E5", "reentrancy"} {
		if !strings.Contains(a, want) {
			t.Errorf("advisory %q is missing %q", a, want)
		}
	}
}

// ---- label-alias map layer ----------------------------------------------

func TestCanonicalClassesIsTheKnownSet(t *testing.T) {
	// no second source of truth: the constant IS known_classes()
	canonical := CanonicalClasses()
	known := KnownClasses()
	if len(canonical) != len(known) {
		t.Fatalf("canonical %d != known %d", len(canonical), len(known))
	}
	for cls := range canonical {
		if _, ok := known[cls]; !ok {
			t.Errorf("canonical class %q is not known", cls)
		}
	}
	if len(canonical) != 20 {
		t.Errorf("canonical class count = %d, want 20", len(canonical))
	}
}

func TestSeededMapFilesAreValid(t *testing.T) {
	useConfig(t, "testdata")
	dir := ConfigDir
	if err := ValidateMapFile(filepath.Join(dir, CommonMapName)); err != nil {
		t.Fatalf("common map: %v", err)
	}
	paths, err := filepath.Glob(filepath.Join(dir, datasetMapGlob))
	if err != nil {
		t.Fatal(err)
	}
	if len(paths) == 0 {
		t.Fatal("the sprint ships per-dataset alias stubs")
	}
	for _, p := range paths {
		if filepath.Base(p) == CommonMapName {
			continue
		}
		if err := ValidateMapFile(p); err != nil {
			t.Errorf("%s: %v", filepath.Base(p), err)
		}
	}
}

func TestNormalizeMappedAliases(t *testing.T) {
	cases := []struct{ label, canonical string }{
		{"Access Control", "access-control"},
		{"  ARITHMETIC ", "precision-rounding"},
		{"denial of service", "dos-griefing"},
		{"time manipulation", "oracle-manipulation"},
		{"flashloan", "flash-loan"},
	}
	useConfig(t, "testdata")
	for _, c := range cases {
		got, mapped, err := NormalizeClass(ptr(c.label), nil)
		if err != nil {
			t.Fatal(err)
		}
		if got != c.canonical || !mapped {
			t.Errorf("normalize_class(%q) = %q, %v; want %q, true",
				c.label, got, mapped, c.canonical)
		}
	}
}

func TestNormalizeIsCaseWhitespaceAndPunctuationInsensitive(t *testing.T) {
	useConfig(t, "testdata")
	a, _, err := NormalizeClass(ptr("Access  Control"), nil)
	if err != nil {
		t.Fatal(err)
	}
	b, bm, err := NormalizeClass(ptr("access-control"), nil)
	if err != nil {
		t.Fatal(err)
	}
	c, cm, err := NormalizeClass(ptr("  ACCESS-control "), nil)
	if err != nil {
		t.Fatal(err)
	}
	if a != "access-control" || b != "access-control" || c != "access-control" {
		t.Errorf("normalize_class variants = %q, %q, %q; want all access-control",
			a, b, c)
	}
	if !bm || !cm {
		t.Errorf("mapped flags = %v, %v; want true, true", bm, cm)
	}
}

func TestNormalizeUnknownFallsBackToUnmapped(t *testing.T) {
	useConfig(t, "testdata")
	for _, label := range []*string{ptr("quantum-decoherence"), ptr(""), nil} {
		got, mapped, err := NormalizeClass(label, nil)
		if err != nil {
			t.Fatal(err)
		}
		if got != UNMAPPED || mapped {
			t.Errorf("normalize_class(%s) = %q, %v; want unmapped, false",
				pyReprPtr(label), got, mapped)
		}
	}
}

func TestExplicitUnmappedAliasIsARecordedDecision(t *testing.T) {
	// 'front-running' has no canonical class: the map records that decision
	// explicitly (honesty over coverage) — mapped stays False.
	useConfig(t, "testdata")
	got, mapped, err := NormalizeClass(ptr("front-running"), nil)
	if err != nil {
		t.Fatal(err)
	}
	if got != UNMAPPED || mapped {
		t.Errorf("normalize_class(front-running) = %q, %v; want unmapped, false",
			got, mapped)
	}
	// the decision is in the shipped map, not an accident of the fallback
	maps, err := LoadMaps(nil)
	if err != nil {
		t.Fatal(err)
	}
	if v := objAt(objAt(maps, "aliases"), "front-running"); v.S != UNMAPPED {
		t.Errorf("taxonomy_map.yaml front-running = %s, want \"unmapped\"",
			validation.CanonCompact(v))
	}
}

func TestCanonicalSelfNameMapsEvenWithoutAlias(t *testing.T) {
	cfg := filepath.Join(t.TempDir(), "config")
	if err := os.MkdirAll(cfg, 0o755); err != nil {
		t.Fatal(err)
	}
	body := "default: unmapped\naliases: {}\n"
	if err := os.WriteFile(filepath.Join(cfg, CommonMapName), []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	useConfig(t, filepath.Dir(cfg))
	maps, err := LoadMaps([]string{})
	if err != nil {
		t.Fatal(err)
	}
	got, mapped, err := NormalizeClass(ptr("Access Control"), &maps)
	if err != nil {
		t.Fatal(err)
	}
	if got != "access-control" || !mapped {
		t.Errorf("normalize_class(Access Control) = %q, %v; want access-control, true",
			got, mapped)
	}
	// a non-canonical label in the same empty map still falls back
	got, mapped, err = NormalizeClass(ptr("whatever-else"), &maps)
	if err != nil {
		t.Fatal(err)
	}
	if got != UNMAPPED || mapped {
		t.Errorf("normalize_class(whatever-else) = %q, %v; want unmapped, false",
			got, mapped)
	}
}

func TestDatasetSpecificAliasWinsOverCommon(t *testing.T) {
	cfg := tmpConfig(t)
	body := "default: unmapped\naliases:\n  custom-label: reentrancy\n"
	if err := os.WriteFile(filepath.Join(cfg, "taxonomy_testds.yaml"),
		[]byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	// loading other datasets (or none of them) leaves the label unmapped
	forge, err := LoadMaps([]string{"forge"})
	if err != nil {
		t.Fatal(err)
	}
	got, mapped, err := NormalizeClass(ptr("custom-label"), &forge)
	if err != nil {
		t.Fatal(err)
	}
	if got != UNMAPPED || mapped {
		t.Errorf("without the dataset: %q, %v; want unmapped, false", got, mapped)
	}
	// with the dataset file in play, its specific alias wins
	testds, err := LoadMaps([]string{"testds"})
	if err != nil {
		t.Fatal(err)
	}
	got, mapped, err = NormalizeClass(ptr("custom-label"), &testds)
	if err != nil {
		t.Fatal(err)
	}
	if got != "reentrancy" || !mapped {
		t.Errorf("with the dataset: %q, %v; want reentrancy, true", got, mapped)
	}
}

func TestMissingDatasetFileIsANormalMiss(t *testing.T) {
	useConfig(t, "testdata")
	maps, err := LoadMaps([]string{"no-such-dataset"})
	if err != nil {
		t.Fatal(err)
	}
	if got := objStr(maps, "default"); got != UNMAPPED {
		t.Errorf("default = %q, want unmapped", got)
	}
	if len(objAt(maps, "aliases").O) == 0 {
		t.Error("the common map is still merged in")
	}
	got, mapped, err := NormalizeClass(ptr("reentrancy"), &maps)
	if err != nil {
		t.Fatal(err)
	}
	if got != "reentrancy" || !mapped {
		t.Errorf("normalize_class(reentrancy) = %q, %v; want reentrancy, true",
			got, mapped)
	}
}

func TestBadMapFileFailsLoud(t *testing.T) {
	cfg := filepath.Join(t.TempDir(), "config")
	if err := os.MkdirAll(cfg, 0o755); err != nil {
		t.Fatal(err)
	}
	bad := filepath.Join(cfg, "taxonomy_bad.yaml")
	if err := os.WriteFile(bad, []byte("aliases:\n  some-label: Defi-Rekt\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	err := ValidateMapFile(bad)
	if err == nil || !strings.Contains(err.Error(), "canonical class") {
		t.Errorf("validate_map_file = %v; want a canonical-class error", err)
	}
	// and load_maps refuses to merge it: a bad map is a deployment error
	useConfig(t, filepath.Dir(cfg))
	if _, err := LoadMaps([]string{"bad"}); err == nil ||
		!strings.Contains(err.Error(), "canonical class") {
		t.Errorf("load_maps = %v; want a canonical-class error", err)
	}
}

func TestMapFileWithBadYAMLFailsLoud(t *testing.T) {
	cfg := filepath.Join(t.TempDir(), "config")
	if err := os.MkdirAll(cfg, 0o755); err != nil {
		t.Fatal(err)
	}
	bad := filepath.Join(cfg, "taxonomy_broken.yaml")
	if err := os.WriteFile(bad, []byte("aliases: [oops\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	err := ValidateMapFile(bad)
	if err == nil || !strings.Contains(err.Error(), "not valid YAML") {
		t.Errorf("validate_map_file = %v; want a not-valid-YAML error", err)
	}
	if err != nil && !strings.HasPrefix(err.Error(), "taxonomy map "+bad+" is not valid YAML: ") {
		t.Errorf("error %q does not carry the map path prefix", err)
	}
}

func TestSimulationModeClassesConfirmAtE6(t *testing.T) {
	// spec 3.2 §4.8: E6 = independent reproduction, reachable on
	// single-chain forks; v1 validation posture.
	if got := findings.CLASS_CONFIRM_FLOOR["share-price-inflation"]; got != "E6" {
		t.Errorf("share-price-inflation floor = %q, want E6", got)
	}
	if got := findings.CLASS_CONFIRM_FLOOR["economic-invariant"]; got != "E6" {
		t.Errorf("economic-invariant floor = %q, want E6", got)
	}
}

// ---- tests/test_taxonomy_seed_alignment.py -------------------------------

// seedBugClassLabels is _seed_bug_class_labels: every distinct bug-class label
// the framework's own seed dataset carries, straight from the committed
// snapshot of sft/examples.json. Assistant messages only: those are the
// model's actual output (the labels the dataset teaches).
func seedBugClassLabels(t *testing.T) []string {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "seed", "examples.json"))
	if err != nil {
		t.Fatal(err)
	}
	var store struct {
		Examples []struct {
			Messages []struct {
				Role    string  `json:"role"`
				Content *string `json:"content"`
			} `json:"messages"`
		} `json:"examples"`
	}
	if err := json.Unmarshal(raw, &store); err != nil {
		t.Fatal(err)
	}
	labels := map[string]struct{}{}
	for _, ex := range store.Examples {
		for _, msg := range ex.Messages {
			if msg.Role != "assistant" {
				continue
			}
			content := ""
			if msg.Content != nil {
				content = *msg.Content
			}
			for _, m := range bugClassRe.FindAllStringSubmatch(content, -1) {
				labels[m[1]+m[2]] = struct{}{}
			}
		}
	}
	return sortedKeys(labels)
}

// bugClassRe is _BUG_CLASS_RE: a bug-class label as the model writes it
// (kebab-case, 4+ chars), inside a JSON "bug_class" field or a
// CONFIRMED/REJECTED line of an assistant message.
var bugClassRe = regexp.MustCompile(
	`"bug_class"\s*:\s*"([a-z0-9][a-z0-9-]{3,})"` +
		`|bug_class:\s*([a-z0-9][a-z0-9-]{3,})\b`)

func TestSeedDatasetCarriesLabels(t *testing.T) {
	labels := seedBugClassLabels(t)
	if len(labels) == 0 {
		t.Fatal("seed dataset should carry bug-class labels")
	}
	// the two known seed labels must be found (guards against the regex
	// silently matching nothing and the test passing vacuously)
	for _, want := range []string{"first-depositor-inflation",
		"stale-oracle-liquidation"} {
		found := false
		for _, l := range labels {
			if l == want {
				found = true
			}
		}
		if !found {
			t.Errorf("seed labels %v do not carry %q", labels, want)
		}
	}
}

func TestSeedLabelsResolveToCanonicalClasses(t *testing.T) {
	useConfig(t, "testdata")
	canonical := CanonicalClasses()
	labels := seedBugClassLabels(t)
	if len(labels) == 0 {
		t.Fatal("no seed labels to check")
	}
	for _, label := range labels {
		got, mapped, err := NormalizeClass(ptr(label), nil)
		if err != nil {
			t.Fatal(err)
		}
		if !mapped {
			t.Errorf("seed label %q is not covered by the taxonomy alias maps "+
				"(it resolves to the default %q)", label, got)
			continue
		}
		if _, ok := canonical[got]; !ok {
			t.Errorf("seed label %q maps to %q, which is not a canonical class",
				label, got)
		}
	}
}

func TestExampleUsesACanonicalClass(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("testdata", "seed",
		"hypothesis.example.json"))
	if err != nil {
		t.Fatal(err)
	}
	payload, err := validation.ParseOrdered(raw)
	if err != nil {
		t.Fatal(err)
	}
	cls := objStr(objAt(payload, "root_cause"), "class")
	if cls == "" {
		t.Fatal("example payload must carry a root_cause.class")
	}
	if _, ok := CanonicalClasses()[cls]; !ok {
		t.Errorf("--example uses non-canonical class %q (canonical: %s)",
			cls, strings.Join(sortedKeys(CanonicalClasses()), ", "))
	}
}

func TestExampleIngestRoundTripsWithoutAdvisory(t *testing.T) {
	// PORT-NOTE: the Python test drives `webv2 ingest --example | webv2 ingest
	// <campaign> --json-file -` through cli.main and reads result
	// ["class_advisory"]; the Go twin's portable equivalent is the intake
	// warning list, which is the same value (the CLI field is fed by it).
	raw, err := os.ReadFile(filepath.Join("testdata", "seed",
		"hypothesis.example.json"))
	if err != nil {
		t.Fatal(err)
	}
	payload, err := validation.ParseOrdered(raw)
	if err != nil {
		t.Fatal(err)
	}
	if warnings := findings.IntakeCheckpoint(payload, "discovery"); len(warnings) != 0 {
		t.Errorf("ingesting the framework's own example produced warnings: %v",
			warnings)
	}
	// the seam is live: an unknown class does produce the advisory
	bad := validation.VObj(kv("root_cause",
		validation.VObj(kv("class", validation.VStr("quantum-decoherence")))))
	warnings := findings.IntakeCheckpoint(bad, "discovery")
	want := ClassAdvisory(ptr("quantum-decoherence"))
	if len(warnings) != 1 || warnings[0] != want {
		t.Errorf("intake warnings = %v, want [%s]", warnings, want)
	}
}

// TestMissingMapErrorMatchesPython pins the deployment-error text (the Python
// twin raises FileNotFoundError with the same message).
func TestMissingMapErrorMatchesPython(t *testing.T) {
	useConfig(t, "testdata")
	_, err := LoadMaps([]string{"no-such-dataset"})
	if err != nil {
		t.Fatalf("a missing per-dataset file is a normal miss, got %v", err)
	}
	path := filepath.Join(t.TempDir(), "nope.yaml")
	err = ValidateMapFile(path)
	if err == nil {
		t.Fatal("validating a missing file must fail")
	}
	if !strings.Contains(err.Error(), "taxonomy map missing: "+path) {
		t.Errorf("error = %q, want the taxonomy map missing prefix", err)
	}
	var missing *MissingMapError
	if !errors.As(err, &missing) || !errors.Is(err, fs.ErrNotExist) {
		t.Errorf("error %v does not report the MissingMapError/fs.ErrNotExist sentinels", err)
	}
}

// ---- byte-exact vectors (generated by the Python twin) -------------------

type normalizeVector struct {
	Label     *string `json:"label"`
	Canonical string  `json:"canonical"`
	Mapped    bool    `json:"mapped"`
}

func TestNormalizeClassVectors(t *testing.T) {
	useConfig(t, "testdata")
	var vectors []normalizeVector
	loadVectors(t, "normalize_class.json", &vectors)
	if len(vectors) < 400 {
		t.Fatalf("vector table too small: %d", len(vectors))
	}
	mapped := 0
	for _, v := range vectors {
		got, gotMapped, err := NormalizeClass(v.Label, nil)
		if err != nil {
			t.Fatalf("normalize_class(%s): %v", pyReprPtr(v.Label), err)
		}
		if got != v.Canonical || gotMapped != v.Mapped {
			t.Errorf("normalize_class(%s) = %q, %v; want %q, %v",
				pyReprPtr(v.Label), got, gotMapped, v.Canonical, v.Mapped)
		}
		if gotMapped {
			mapped++
		}
	}
	if mapped == 0 {
		t.Error("no vector mapped to a canonical class; the table is vacuous")
	}
}

type classReportVector struct {
	Label      *string `json:"label"`
	ReportJSON string  `json:"report_json"`
}

func TestClassReportVectors(t *testing.T) {
	var vectors []classReportVector
	loadVectors(t, "class_report.json", &vectors)
	if len(vectors) < 50 {
		t.Fatalf("vector table too small: %d", len(vectors))
	}
	known := 0
	for _, v := range vectors {
		report := ClassReport(v.Label)
		if got := validation.CanonCompact(report); got != v.ReportJSON {
			t.Errorf("class_report(%s) = %s\n want %s",
				pyReprPtr(v.Label), got, v.ReportJSON)
		}
		if objAt(report, "known").B {
			known++
		}
	}
	if known == 0 || known == len(vectors) {
		t.Errorf("known/unknown split = %d/%d; want a mix", known, len(vectors))
	}
}

type classAdvisoryVector struct {
	Label    *string `json:"label"`
	Advisory *string `json:"advisory"`
}

func TestClassAdvisoryVectors(t *testing.T) {
	var vectors []classAdvisoryVector
	loadVectors(t, "class_advisory.json", &vectors)
	if len(vectors) < 5 {
		t.Fatalf("vector table too small: %d", len(vectors))
	}
	nonEmpty := 0
	for _, v := range vectors {
		want := ""
		if v.Advisory != nil {
			want = *v.Advisory
		}
		if got := ClassAdvisory(v.Label); got != want {
			t.Errorf("class_advisory(%s):\n got %q\nwant %q",
				pyReprPtr(v.Label), got, want)
		}
		if want != "" {
			nonEmpty++
		}
	}
	if nonEmpty == 0 {
		t.Error("every advisory vector is empty; the table is vacuous")
	}
}

type closeMatchVector struct {
	Word          string   `json:"word"`
	Possibilities []string `json:"possibilities"`
	Matches       []string `json:"matches"`
}

func TestCloseMatchesVectors(t *testing.T) {
	var vectors []closeMatchVector
	loadVectors(t, "close_matches.json", &vectors)
	if len(vectors) < 35 {
		t.Fatalf("vector table too small: %d", len(vectors))
	}
	hit := 0
	for _, v := range vectors {
		got := closeMatches(v.Word, v.Possibilities, 3, 0.6)
		if !equalStrings(got, v.Matches) {
			t.Errorf("close_matches(%q) = %v, want %v", v.Word, got, v.Matches)
		}
		if len(got) > 0 {
			hit++
		}
	}
	if hit == 0 {
		t.Error("no word matched anything; the table is vacuous")
	}
}

type ratioVector struct {
	A         string  `json:"a"`
	B         string  `json:"b"`
	Ratio     float64 `json:"ratio"`
	Quick     float64 `json:"quick"`
	RealQuick float64 `json:"real_quick"`
}

func TestRatioVectors(t *testing.T) {
	var vectors []ratioVector
	loadVectors(t, "ratios.json", &vectors)
	if len(vectors) < 15 {
		t.Fatalf("vector table too small: %d", len(vectors))
	}
	nonTrivial := 0
	for _, v := range vectors {
		// CPython and Go both do 2.0*M/T in IEEE doubles: bit-identical.
		if got := seqRatio(v.A, v.B); got != v.Ratio {
			t.Errorf("ratio(%q, %q) = %.17g, want %.17g", v.A, v.B, got, v.Ratio)
		}
		if got := quickRatio(v.A, v.B); got != v.Quick {
			t.Errorf("quick_ratio(%q, %q) = %.17g, want %.17g", v.A, v.B, got, v.Quick)
		}
		if got := realQuickRatio(v.A, v.B); got != v.RealQuick {
			t.Errorf("real_quick_ratio(%q, %q) = %.17g, want %.17g",
				v.A, v.B, got, v.RealQuick)
		}
		if v.Ratio > 0 && v.Ratio < 1 {
			nonTrivial++
		}
	}
	if nonTrivial == 0 {
		t.Error("every ratio is 0 or 1; the table does not exercise the matcher")
	}
}

func TestLoadMapsVectors(t *testing.T) {
	useConfig(t, "testdata")
	var vectors map[string]string
	loadVectors(t, "maps.json", &vectors)
	cases := []struct {
		name     string
		datasets []string
	}{
		{"all", nil},
		{"none", []string{}},
		{"forge", []string{"forge"}},
		{"missing", []string{"no-such-dataset"}},
		{"scabench", []string{"scabench"}},
	}
	if len(vectors) != len(cases) {
		t.Fatalf("vector variants = %d, want %d", len(vectors), len(cases))
	}
	for _, c := range cases {
		maps, err := LoadMaps(c.datasets)
		if err != nil {
			t.Fatalf("%s: %v", c.name, err)
		}
		if got := validation.CanonCompact(maps); got != vectors[c.name] {
			t.Errorf("load_maps(%v) = %s\n want %s", c.datasets, got, vectors[c.name])
		}
	}
}

type mapFileVector struct {
	Name      string  `json:"name"`
	Text      *string `json:"text"`
	ErrorKind *string `json:"error_kind"`
	Error     *string `json:"error"`
	MapJSON   *string `json:"map_json"`
}

func TestMapFileVectors(t *testing.T) {
	var vectors []mapFileVector
	loadVectors(t, "taxonomy_errors.json", &vectors)
	if len(vectors) < 20 {
		t.Fatalf("vector table too small: %d", len(vectors))
	}
	ok, failed := 0, 0
	for _, v := range vectors {
		dir := t.TempDir()
		path := filepath.Join(dir, v.Name)
		if v.Text != nil {
			if err := os.WriteFile(path, []byte(*v.Text), 0o644); err != nil {
				t.Fatal(err)
			}
		}
		if v.ErrorKind == nil {
			data, err := readMapFile(path)
			if err != nil {
				t.Errorf("%s: unexpected error %v", v.Name, err)
				continue
			}
			ok++
			if v.MapJSON != nil {
				if got := validation.CanonCompact(mapValue(data)); got != *v.MapJSON {
					t.Errorf("%s: map = %s\n want %s", v.Name, got, *v.MapJSON)
				}
			}
			continue
		}
		// the fail-loud deployment check (a missing file is an error here,
		// where read_map_file treats absence as a miss)
		err := ValidateMapFile(path)
		if err == nil {
			t.Errorf("%s: want %s, got no error", v.Name, *v.Error)
			continue
		}
		failed++
		want := strings.ReplaceAll(*v.Error, "{dir}", dir)
		if *v.ErrorKind == "FileNotFoundError" {
			if !errors.Is(err, fs.ErrNotExist) {
				t.Errorf("%s: error %v is not fs.ErrNotExist", v.Name, err)
			}
			continue
		}
		// The YAML parser's own text is PyYAML's, which yaml.v3 cannot
		// reproduce (reported as a deviation); the prefix is byte-exact.
		if strings.HasSuffix(want, "is not valid YAML: ") ||
			strings.Contains(want, "is not valid YAML:") {
			prefix := want[:strings.Index(want, "is not valid YAML:")+len("is not valid YAML: ")]
			if !strings.HasPrefix(err.Error(), prefix) {
				t.Errorf("%s: error %q lacks the prefix %q", v.Name, err, prefix)
			}
			continue
		}
		if err.Error() != want {
			t.Errorf("%s:\n got %q\nwant %q", v.Name, err.Error(), want)
		}
	}
	if ok < 5 || failed < 10 {
		t.Errorf("vector mix = %d ok / %d failed; want both cases", ok, failed)
	}
}
