// Code generated from .scratch/oq3/probe.py output (Python
// jsonschema 4.26.0, CPython 3.14) over all 27 schemas. DO NOT
// EDIT BY HAND; regenerate with .scratch/oq3/gen_golden.py.
package validation

import (
	"errors"
	"testing"
)

type goldenRow struct {
	schema  string
	label   string
	data    string // JSON
	expect  string // "" = valid, else exact SchemaError text (max_errors=1)
	expect3 string // exact text at max_errors=3, "" = same as expect or valid
}

var goldenRows = []goldenRow{
	{schema: "archetype", label: "g_arr", data: "[1]",
		expect: "archetype validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "archetype validation failed at <root>: [1] is not of type 'object'"},
	{schema: "archetype", label: "g_float", data: "3.14",
		expect: "archetype validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "archetype validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "archetype", label: "g_int", data: "42",
		expect: "archetype validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "archetype validation failed at <root>: 42 is not of type 'object'"},
	{schema: "archetype", label: "g_null", data: "null",
		expect: "archetype validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "archetype validation failed at <root>: None is not of type 'object'"},
	{schema: "archetype", label: "g_obj", data: "{}",
		expect: "archetype validation failed at <root>: 'id' is a required property (+3 more errors)", expect3: "archetype validation failed at <root>: 'id' is a required property\n  also at <root>: 'name' is a required property\n  also at <root>: 'criticality' is a required property\n  (+1 more errors)"},
	{schema: "archetype", label: "g_str", data: "\"str\"",
		expect: "archetype validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "archetype validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "archetype", label: "g_true", data: "true",
		expect: "archetype validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "archetype validation failed at <root>: True is not of type 'object'"},
	{schema: "archetype", label: "oneof_both_fail", data: "{\"id\":\"AT-1\",\"name\":\"bridge-drain\",\"checks\":[{\"type\":\"state_var_exists\"}]}",
		expect: "archetype validation failed at <root>: 'criticality' is a required property (+2 more errors)", expect3: "archetype validation failed at <root>: 'criticality' is a required property\n  also at checks/0: {'type': 'state_var_exists'} is not valid under any of the given schemas\n  also at id: 'AT-1' does not match '^[a-z0-9][a-z0-9-]{2,40}$'"},
	{schema: "archetype", label: "oneof_extra_prop", data: "{\"id\":\"AT-1\",\"name\":\"bridge-drain\",\"checks\":[{\"type\":\"state_var_exists\",\"names\":[\"a\"],\"extra\":1}]}",
		expect: "archetype validation failed at <root>: 'criticality' is a required property (+2 more errors)", expect3: "archetype validation failed at <root>: 'criticality' is a required property\n  also at checks/0: {'type': 'state_var_exists', 'names': ['a'], 'extra': 1} is not valid under any of the given schemas\n  also at id: 'AT-1' does not match '^[a-z0-9][a-z0-9-]{2,40}$'"},
	{schema: "archetype", label: "oneof_valid", data: "{\"id\":\"AT-1\",\"name\":\"bridge-drain\",\"checks\":[{\"type\":\"state_var_exists\",\"names\":[\"a\"]}]}",
		expect: "archetype validation failed at <root>: 'criticality' is a required property (+1 more errors)", expect3: "archetype validation failed at <root>: 'criticality' is a required property\n  also at id: 'AT-1' does not match '^[a-z0-9][a-z0-9-]{2,40}$'"},
	{schema: "assumption", label: "g_arr", data: "[1]",
		expect: "assumption validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "assumption validation failed at <root>: [1] is not of type 'object'"},
	{schema: "assumption", label: "g_float", data: "3.14",
		expect: "assumption validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "assumption validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "assumption", label: "g_int", data: "42",
		expect: "assumption validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "assumption validation failed at <root>: 42 is not of type 'object'"},
	{schema: "assumption", label: "g_null", data: "null",
		expect: "assumption validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "assumption validation failed at <root>: None is not of type 'object'"},
	{schema: "assumption", label: "g_obj", data: "{}",
		expect: "assumption validation failed at <root>: 'id' is a required property (+5 more errors)", expect3: "assumption validation failed at <root>: 'id' is a required property\n  also at <root>: 'type' is a required property\n  also at <root>: 'claim' is a required property\n  (+3 more errors)"},
	{schema: "assumption", label: "g_str", data: "\"str\"",
		expect: "assumption validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "assumption validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "assumption", label: "g_true", data: "true",
		expect: "assumption validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "assumption validation failed at <root>: True is not of type 'object'"},
	{schema: "bounty_policy", label: "g_arr", data: "[1]",
		expect: "bounty_policy validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "bounty_policy validation failed at <root>: [1] is not of type 'object'"},
	{schema: "bounty_policy", label: "g_float", data: "3.14",
		expect: "bounty_policy validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "bounty_policy validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "bounty_policy", label: "g_int", data: "42",
		expect: "bounty_policy validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "bounty_policy validation failed at <root>: 42 is not of type 'object'"},
	{schema: "bounty_policy", label: "g_null", data: "null",
		expect: "bounty_policy validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "bounty_policy validation failed at <root>: None is not of type 'object'"},
	{schema: "bounty_policy", label: "g_obj", data: "{}",
		expect: "bounty_policy validation failed at <root>: 'program' is a required property (+5 more errors)", expect3: "bounty_policy validation failed at <root>: 'program' is a required property\n  also at <root>: 'program_url' is a required property\n  also at <root>: 'chains' is a required property\n  (+3 more errors)"},
	{schema: "bounty_policy", label: "g_str", data: "\"str\"",
		expect: "bounty_policy validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "bounty_policy validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "bounty_policy", label: "g_true", data: "true",
		expect: "bounty_policy validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "bounty_policy validation failed at <root>: True is not of type 'object'"},
	{schema: "campaign_plan", label: "g_arr", data: "[1]",
		expect: "campaign_plan validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "campaign_plan validation failed at <root>: [1] is not of type 'object'"},
	{schema: "campaign_plan", label: "g_float", data: "3.14",
		expect: "campaign_plan validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "campaign_plan validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "campaign_plan", label: "g_int", data: "42",
		expect: "campaign_plan validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "campaign_plan validation failed at <root>: 42 is not of type 'object'"},
	{schema: "campaign_plan", label: "g_null", data: "null",
		expect: "campaign_plan validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "campaign_plan validation failed at <root>: None is not of type 'object'"},
	{schema: "campaign_plan", label: "g_obj", data: "{}",
		expect: "campaign_plan validation failed at <root>: 'campaign_id' is a required property (+2 more errors)", expect3: "campaign_plan validation failed at <root>: 'campaign_id' is a required property\n  also at <root>: 'created_at' is a required property\n  also at <root>: 'priorities' is a required property"},
	{schema: "campaign_plan", label: "g_str", data: "\"str\"",
		expect: "campaign_plan validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "campaign_plan validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "campaign_plan", label: "g_true", data: "true",
		expect: "campaign_plan validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "campaign_plan validation failed at <root>: True is not of type 'object'"},
	{schema: "campaign_state", label: "g_arr", data: "[1]",
		expect: "campaign_state validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "campaign_state validation failed at <root>: [1] is not of type 'object'"},
	{schema: "campaign_state", label: "g_float", data: "3.14",
		expect: "campaign_state validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "campaign_state validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "campaign_state", label: "g_int", data: "42",
		expect: "campaign_state validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "campaign_state validation failed at <root>: 42 is not of type 'object'"},
	{schema: "campaign_state", label: "g_null", data: "null",
		expect: "campaign_state validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "campaign_state validation failed at <root>: None is not of type 'object'"},
	{schema: "campaign_state", label: "g_obj", data: "{}",
		expect: "campaign_state validation failed at <root>: 'campaign_id' is a required property (+4 more errors)", expect3: "campaign_state validation failed at <root>: 'campaign_id' is a required property\n  also at <root>: 'program' is a required property\n  also at <root>: 'created_at' is a required property\n  (+2 more errors)"},
	{schema: "campaign_state", label: "g_str", data: "\"str\"",
		expect: "campaign_state validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "campaign_state validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "campaign_state", label: "g_true", data: "true",
		expect: "campaign_state validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "campaign_state validation failed at <root>: True is not of type 'object'"},
	{schema: "chain", label: "g_arr", data: "[1]",
		expect: "chain validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "chain validation failed at <root>: [1] is not of type 'object'"},
	{schema: "chain", label: "g_float", data: "3.14",
		expect: "chain validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "chain validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "chain", label: "g_int", data: "42",
		expect: "chain validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "chain validation failed at <root>: 42 is not of type 'object'"},
	{schema: "chain", label: "g_null", data: "null",
		expect: "chain validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "chain validation failed at <root>: None is not of type 'object'"},
	{schema: "chain", label: "g_obj", data: "{}",
		expect: "chain validation failed at <root>: 'chain_id' is a required property (+7 more errors)", expect3: "chain validation failed at <root>: 'chain_id' is a required property\n  also at <root>: 'chain_signature' is a required property\n  also at <root>: 'campaign_id' is a required property\n  (+5 more errors)"},
	{schema: "chain", label: "g_str", data: "\"str\"",
		expect: "chain validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "chain validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "chain", label: "g_true", data: "true",
		expect: "chain validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "chain validation failed at <root>: True is not of type 'object'"},
	{schema: "coverage", label: "g_arr", data: "[1]",
		expect: "coverage validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "coverage validation failed at <root>: [1] is not of type 'object'"},
	{schema: "coverage", label: "g_float", data: "3.14",
		expect: "coverage validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "coverage validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "coverage", label: "g_int", data: "42",
		expect: "coverage validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "coverage validation failed at <root>: 42 is not of type 'object'"},
	{schema: "coverage", label: "g_null", data: "null",
		expect: "coverage validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "coverage validation failed at <root>: None is not of type 'object'"},
	{schema: "coverage", label: "g_obj", data: "{}",
		expect: "coverage validation failed at <root>: 'campaign_id' is a required property (+3 more errors)", expect3: "coverage validation failed at <root>: 'campaign_id' is a required property\n  also at <root>: 'snapshot_id' is a required property\n  also at <root>: 'contracts' is a required property\n  (+1 more errors)"},
	{schema: "coverage", label: "g_str", data: "\"str\"",
		expect: "coverage validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "coverage validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "coverage", label: "g_true", data: "true",
		expect: "coverage validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "coverage validation failed at <root>: True is not of type 'object'"},
	{schema: "drift_report", label: "g_arr", data: "[1]",
		expect: "drift_report validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "drift_report validation failed at <root>: [1] is not of type 'object'"},
	{schema: "drift_report", label: "g_float", data: "3.14",
		expect: "drift_report validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "drift_report validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "drift_report", label: "g_int", data: "42",
		expect: "drift_report validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "drift_report validation failed at <root>: 42 is not of type 'object'"},
	{schema: "drift_report", label: "g_null", data: "null",
		expect: "drift_report validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "drift_report validation failed at <root>: None is not of type 'object'"},
	{schema: "drift_report", label: "g_obj", data: "{}",
		expect: "drift_report validation failed at <root>: 'campaign_id' is a required property (+2 more errors)", expect3: "drift_report validation failed at <root>: 'campaign_id' is a required property\n  also at <root>: 'snapshot_id' is a required property\n  also at <root>: 'drifts' is a required property"},
	{schema: "drift_report", label: "g_str", data: "\"str\"",
		expect: "drift_report validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "drift_report validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "drift_report", label: "g_true", data: "true",
		expect: "drift_report validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "drift_report validation failed at <root>: True is not of type 'object'"},
	{schema: "evaluation_case", label: "g_arr", data: "[1]",
		expect: "evaluation_case validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "evaluation_case validation failed at <root>: [1] is not of type 'object'"},
	{schema: "evaluation_case", label: "g_float", data: "3.14",
		expect: "evaluation_case validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "evaluation_case validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "evaluation_case", label: "g_int", data: "42",
		expect: "evaluation_case validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "evaluation_case validation failed at <root>: 42 is not of type 'object'"},
	{schema: "evaluation_case", label: "g_null", data: "null",
		expect: "evaluation_case validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "evaluation_case validation failed at <root>: None is not of type 'object'"},
	{schema: "evaluation_case", label: "g_obj", data: "{}",
		expect: "evaluation_case validation failed at <root>: 'case_id' is a required property (+7 more errors)", expect3: "evaluation_case validation failed at <root>: 'case_id' is a required property\n  also at <root>: 'source' is a required property\n  also at <root>: 'partition' is a required property\n  (+5 more errors)"},
	{schema: "evaluation_case", label: "g_str", data: "\"str\"",
		expect: "evaluation_case validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "evaluation_case validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "evaluation_case", label: "g_true", data: "true",
		expect: "evaluation_case validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "evaluation_case validation failed at <root>: True is not of type 'object'"},
	{schema: "finding", label: "affected_empty", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\",\"affected\":[]}",
		expect: "finding validation failed at affected: [] should be non-empty (+0 more errors)", expect3: "finding validation failed at affected: [] should be non-empty"},
	{schema: "finding", label: "assumption_belief_over", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\",\"assumptions\":[{\"id\":\"A1\",\"type\":\"reachability\",\"claim\":\"the attacker can call withdraw twice\",\"status\":\"UNKNOWN\",\"model_belief\":1.5,\"blocking\":true}]}",
		expect: "finding validation failed at assumptions/0/model_belief: 1.5 is greater than the maximum of 1 (+0 more errors)", expect3: "finding validation failed at assumptions/0/model_belief: 1.5 is greater than the maximum of 1"},
	{schema: "finding", label: "bad_assumption", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\",\"assumptions\":[{\"id\":\"A-1\",\"type\":\"vibe\",\"claim\":\"short claim\",\"status\":\"UNKNOWN\",\"model_belief\":0.5,\"blocking\":true}]}",
		expect: "finding validation failed at assumptions/0/id: 'A-1' does not match '^A[0-9]{1,4}$' (+1 more errors)", expect3: "finding validation failed at assumptions/0/id: 'A-1' does not match '^A[0-9]{1,4}$'\n  also at assumptions/0/type: 'vibe' is not one of ['reachability', 'authority', 'control', 'state', 'invariant', 'economic', 'environment', 'temporal', 'cross_domain']"},
	{schema: "finding", label: "bad_campaign_id", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-ABC\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\"}",
		expect: "finding validation failed at campaign_id: 'C-ABC' does not match '^C-[0-9a-z]{8,16}$' (+0 more errors)", expect3: "finding validation failed at campaign_id: 'C-ABC' does not match '^C-[0-9a-z]{8,16}$'"},
	{schema: "finding", label: "bad_capability", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\",\"capabilities\":{\"granted\":[\"ab\"]}}",
		expect: "finding validation failed at capabilities/granted/0: 'ab' is too short (+0 more errors)", expect3: "finding validation failed at capabilities/granted/0: 'ab' is too short"},
	{schema: "finding", label: "bad_cwe", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\",\"cwe\":\"CWE-abc\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\"}",
		expect: "finding validation failed at root_cause/cwe: 'CWE-abc' does not match '^CWE-[0-9]+$' (+0 more errors)", expect3: "finding validation failed at root_cause/cwe: 'CWE-abc' does not match '^CWE-[0-9]+$'"},
	{schema: "finding", label: "bad_dedup_sig", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{\"technical_signature\":\"XYZ\"},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\"}",
		expect: "finding validation failed at dedup/technical_signature: 'XYZ' does not match '^[0-9a-f]{16}$' (+0 more errors)", expect3: "finding validation failed at dedup/technical_signature: 'XYZ' does not match '^[0-9a-f]{16}$'"},
	{schema: "finding", label: "bad_evidence", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[{\"evidence_id\":\"EV-OK\",\"level\":\"E9\",\"type\":\"reasoning\",\"description\":\"desc ok\"}],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\"}",
		expect: "finding validation failed at evidence/0/level: 'E9' is not one of ['E0', 'E1', 'E2', 'E3', 'E4', 'E5', 'E6', 'E7'] (+0 more errors)", expect3: "finding validation failed at evidence/0/level: 'E9' is not one of ['E0', 'E1', 'E2', 'E3', 'E4', 'E5', 'E6', 'E7']"},
	{schema: "finding", label: "bad_finding_id", data: "{\"finding_id\":\"F-XYZ\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\"}",
		expect: "finding validation failed at finding_id: 'F-XYZ' does not match '^F-[0-9a-f]{12}$' (+0 more errors)", expect3: "finding validation failed at finding_id: 'F-XYZ' does not match '^F-[0-9a-f]{12}$'"},
	{schema: "finding", label: "bad_history_reason", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[{\"at\":\"2026-01-01T00:00:00Z\",\"from\":\"HYPOTHESIS\",\"to\":\"POSSIBLE\",\"reason\":\"x\"}],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\"}",
		expect: "finding validation failed at history/0/reason: 'x' is too short (+0 more errors)", expect3: "finding validation failed at history/0/reason: 'x' is too short"},
	{schema: "finding", label: "bad_line", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\",\"affected\":[{\"path\":\"p\",\"lines\":[0]}]}",
		expect: "finding validation failed at affected/0/lines/0: 0 is less than the minimum of 1 (+0 more errors)", expect3: "finding validation failed at affected/0/lines/0: 0 is less than the minimum of 1"},
	{schema: "finding", label: "bad_price_basis", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\",\"economic_impact\":{\"price_basis\":\"PRC-xy\"}}",
		expect: "finding validation failed at economic_impact/price_basis: 'PRC-xy' does not match '^PRC-[a-z0-9]{6,}$' (+0 more errors)", expect3: "finding validation failed at economic_impact/price_basis: 'PRC-xy' does not match '^PRC-[a-z0-9]{6,}$'"},
	{schema: "finding", label: "bad_risk_band", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{\"validated\":{\"band\":\"apocalyptic\"}},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\"}",
		expect: "finding validation failed at risk/validated/band: 'apocalyptic' is not one of ['critical', 'high', 'medium', 'low', 'informational'] (+0 more errors)", expect3: "finding validation failed at risk/validated/band: 'apocalyptic' is not one of ['critical', 'high', 'medium', 'low', 'informational']"},
	{schema: "finding", label: "bad_severity", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\",\"reported_severity\":\"ultra\"}",
		expect: "finding validation failed at reported_severity: 'ultra' is not one of ['low', 'medium', 'high', 'critical'] (+0 more errors)", expect3: "finding validation failed at reported_severity: 'ultra' is not one of ['low', 'medium', 'high', 'critical']"},
	{schema: "finding", label: "bad_status", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"BOGUS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\"}",
		expect: "finding validation failed at status: 'BOGUS' is not one of ['HYPOTHESIS', 'NEEDS_RESEARCH', 'PROVISIONALLY_VALID', 'POSSIBLE', 'CONFIRMED', 'DISPROVED', 'DUPLICATE', 'OUT_OF_SCOPE', 'INFORMATIONAL', 'CHAIN'] (+0 more errors)", expect3: "finding validation failed at status: 'BOGUS' is not one of ['HYPOTHESIS', 'NEEDS_RESEARCH', 'PROVISIONALLY_VALID', 'POSSIBLE', 'CONFIRMED', 'DISPROVED', 'DUPLICATE', 'OUT_OF_SCOPE', 'INFORMATIONAL', 'CHAIN']"},
	{schema: "finding", label: "bad_timestamp", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"yesterday\",\"updated_at\":\"2026-01-01T00:00:00Z\"}",
		expect: "finding validation failed at created_at: 'yesterday' does not match '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\\\.[0-9]+)?(Z|[+-][0-9]{2}:[0-9]{2})$' (+0 more errors)", expect3: "finding validation failed at created_at: 'yesterday' does not match '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\\\.[0-9]+)?(Z|[+-][0-9]{2}:[0-9]{2})$'"},
	{schema: "finding", label: "bad_trajectory", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"vibe\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\"}",
		expect: "finding validation failed at trajectory: 'vibe' is not one of ['code', 'economic', 'state-machine', 'attacker', 'historical', 'integration', 'drift', 'lifecycle', 'chain', 'model'] (+0 more errors)", expect3: "finding validation failed at trajectory: 'vibe' is not one of ['code', 'economic', 'state-machine', 'attacker', 'historical', 'integration', 'drift', 'lifecycle', 'chain', 'model']"},
	{schema: "finding", label: "claim_version_fractional", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\",\"claim_version\":1.5}",
		expect: "finding validation failed at claim_version: 1.5 is not of type 'integer' (+0 more errors)", expect3: "finding validation failed at claim_version: 1.5 is not of type 'integer'"},
	{schema: "finding", label: "dedup_cand_verdict", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{\"candidate_verdicts\":{\"F-0123456789ab\":\"maybe\"}},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\"}",
		expect: "finding validation failed at dedup/candidate_verdicts/F-0123456789ab: 'maybe' is not one of ['same', 'distinct'] (+0 more errors)", expect3: "finding validation failed at dedup/candidate_verdicts/F-0123456789ab: 'maybe' is not one of ['same', 'distinct']"},
	{schema: "finding", label: "evidence_missing_desc", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[{\"evidence_id\":\"EV-OK\",\"level\":\"E1\",\"type\":\"reasoning\"}],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\"}",
		expect: "finding validation failed at evidence/0: 'description' is a required property (+0 more errors)", expect3: "finding validation failed at evidence/0: 'description' is a required property"},
	{schema: "finding", label: "extra_prop", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\",\"bogus\":1}",
		expect: "finding validation failed at <root>: Additional properties are not allowed ('bogus' was unexpected) (+0 more errors)", expect3: "finding validation failed at <root>: Additional properties are not allowed ('bogus' was unexpected)"},
	{schema: "finding", label: "good_assumption", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\",\"assumptions\":[{\"id\":\"A1\",\"type\":\"reachability\",\"claim\":\"the attacker can call withdraw twice\",\"status\":\"UNKNOWN\",\"model_belief\":0.5,\"blocking\":true}]}",
		expect: "", expect3: ""},
	{schema: "finding", label: "history_not_array", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":{},\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\"}",
		expect: "finding validation failed at history: {} is not of type 'array' (+0 more errors)", expect3: "finding validation failed at history: {} is not of type 'array'"},
	{schema: "finding", label: "long_title", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\"}",
		expect: "finding validation failed at title: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' is too long (+0 more errors)", expect3: "finding validation failed at title: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' is too long"},
	{schema: "finding", label: "missing_two_required", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\"}",
		expect: "finding validation failed at <root>: 'risk' is a required property (+1 more errors)", expect3: "finding validation failed at <root>: 'risk' is a required property\n  also at <root>: 'dedup' is a required property"},
	{schema: "finding", label: "null_cwe", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\",\"cwe\":null},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\"}",
		expect: "", expect3: ""},
	{schema: "finding", label: "pass_bool", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\",\"pass\":true}",
		expect: "finding validation failed at pass: True is not of type 'integer' (+0 more errors)", expect3: "finding validation failed at pass: True is not of type 'integer'"},
	{schema: "finding", label: "pass_float", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\",\"pass\":1.0}",
		expect: "", expect3: ""},
	{schema: "finding", label: "pass_zero", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\",\"pass\":0}",
		expect: "finding validation failed at pass: 0 is less than the minimum of 1 (+0 more errors)", expect3: "finding validation failed at pass: 0 is less than the minimum of 1"},
	{schema: "finding", label: "risk_prior_neg", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{\"prior\":{\"score\":-0.1}},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\"}",
		expect: "finding validation failed at risk/prior/score: -0.1 is less than the minimum of 0 (+0 more errors)", expect3: "finding validation failed at risk/prior/score: -0.1 is less than the minimum of 0"},
	{schema: "finding", label: "risk_prior_over", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{\"prior\":{\"score\":1.1}},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\"}",
		expect: "finding validation failed at risk/prior/score: 1.1 is greater than the maximum of 1 (+0 more errors)", expect3: "finding validation failed at risk/prior/score: 1.1 is greater than the maximum of 1"},
	{schema: "finding", label: "root_cause_not_object", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":\"oops\",\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\"}",
		expect: "finding validation failed at root_cause: 'oops' is not of type 'object' (+0 more errors)", expect3: "finding validation failed at root_cause: 'oops' is not of type 'object'"},
	{schema: "finding", label: "short_title", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"short\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\"}",
		expect: "finding validation failed at title: 'short' is too short (+0 more errors)", expect3: "finding validation failed at title: 'short' is too short"},
	{schema: "finding", label: "two_extra_props", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\",\"more\":2,\"bogus\":1}",
		expect: "finding validation failed at <root>: Additional properties are not allowed ('bogus', 'more' were unexpected) (+0 more errors)", expect3: "finding validation failed at <root>: Additional properties are not allowed ('bogus', 'more' were unexpected)"},
	{schema: "finding", label: "valid", data: "{\"finding_id\":\"F-0123456789ab\",\"campaign_id\":\"C-abc123def456\",\"snapshot_ids\":{\"source\":\"abc123def456\"},\"title\":\"Reentrancy in withdraw\",\"status\":\"HYPOTHESIS\",\"trajectory\":\"code\",\"root_cause\":{\"class\":\"reentrancy\",\"description\":\"withdraw allows reentrant calls\"},\"attacker\":{\"profile\":\"arbitrary EOA\",\"capabilities\":[]},\"evidence\":[],\"risk\":{},\"dedup\":{},\"history\":[],\"created_at\":\"2026-01-01T00:00:00Z\",\"updated_at\":\"2026-01-01T00:00:00Z\"}",
		expect: "", expect3: ""},
	{schema: "memory", label: "g_arr", data: "[1]",
		expect: "memory validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "memory validation failed at <root>: [1] is not of type 'object'"},
	{schema: "memory", label: "g_float", data: "3.14",
		expect: "memory validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "memory validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "memory", label: "g_int", data: "42",
		expect: "memory validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "memory validation failed at <root>: 42 is not of type 'object'"},
	{schema: "memory", label: "g_null", data: "null",
		expect: "memory validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "memory validation failed at <root>: None is not of type 'object'"},
	{schema: "memory", label: "g_obj", data: "{}",
		expect: "memory validation failed at <root>: 'memory_id' is a required property (+6 more errors)", expect3: "memory validation failed at <root>: 'memory_id' is a required property\n  also at <root>: 'campaign_id' is a required property\n  also at <root>: 'kind' is a required property\n  (+4 more errors)"},
	{schema: "memory", label: "g_str", data: "\"str\"",
		expect: "memory validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "memory validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "memory", label: "g_true", data: "true",
		expect: "memory validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "memory validation failed at <root>: True is not of type 'object'"},
	{schema: "model_request", label: "g_arr", data: "[1]",
		expect: "model_request validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "model_request validation failed at <root>: [1] is not of type 'object'"},
	{schema: "model_request", label: "g_float", data: "3.14",
		expect: "model_request validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "model_request validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "model_request", label: "g_int", data: "42",
		expect: "model_request validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "model_request validation failed at <root>: 42 is not of type 'object'"},
	{schema: "model_request", label: "g_null", data: "null",
		expect: "model_request validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "model_request validation failed at <root>: None is not of type 'object'"},
	{schema: "model_request", label: "g_obj", data: "{}",
		expect: "model_request validation failed at <root>: 'role' is a required property (+4 more errors)", expect3: "model_request validation failed at <root>: 'role' is a required property\n  also at <root>: 'model_id' is a required property\n  also at <root>: 'prompt_version' is a required property\n  (+2 more errors)"},
	{schema: "model_request", label: "g_str", data: "\"str\"",
		expect: "model_request validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "model_request validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "model_request", label: "g_true", data: "true",
		expect: "model_request validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "model_request validation failed at <root>: True is not of type 'object'"},
	{schema: "model_response", label: "g_arr", data: "[1]",
		expect: "", expect3: ""},
	{schema: "model_response", label: "g_float", data: "3.14",
		expect: "", expect3: ""},
	{schema: "model_response", label: "g_int", data: "42",
		expect: "", expect3: ""},
	{schema: "model_response", label: "g_null", data: "null",
		expect: "", expect3: ""},
	{schema: "model_response", label: "g_obj", data: "{}",
		expect: "", expect3: ""},
	{schema: "model_response", label: "g_str", data: "\"str\"",
		expect: "", expect3: ""},
	{schema: "model_response", label: "g_true", data: "true",
		expect: "", expect3: ""},
	{schema: "playbook", label: "g_arr", data: "[1]",
		expect: "playbook validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "playbook validation failed at <root>: [1] is not of type 'object'"},
	{schema: "playbook", label: "g_float", data: "3.14",
		expect: "playbook validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "playbook validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "playbook", label: "g_int", data: "42",
		expect: "playbook validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "playbook validation failed at <root>: 42 is not of type 'object'"},
	{schema: "playbook", label: "g_null", data: "null",
		expect: "playbook validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "playbook validation failed at <root>: None is not of type 'object'"},
	{schema: "playbook", label: "g_obj", data: "{}",
		expect: "playbook validation failed at <root>: 'bug_class' is a required property (+5 more errors)", expect3: "playbook validation failed at <root>: 'bug_class' is a required property\n  also at <root>: 'title' is a required property\n  also at <root>: 'description' is a required property\n  (+3 more errors)"},
	{schema: "playbook", label: "g_str", data: "\"str\"",
		expect: "playbook validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "playbook validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "playbook", label: "g_true", data: "true",
		expect: "playbook validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "playbook validation failed at <root>: True is not of type 'object'"},
	{schema: "price_table", label: "g_arr", data: "[1]",
		expect: "price_table validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "price_table validation failed at <root>: [1] is not of type 'object'"},
	{schema: "price_table", label: "g_float", data: "3.14",
		expect: "price_table validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "price_table validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "price_table", label: "g_int", data: "42",
		expect: "price_table validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "price_table validation failed at <root>: 42 is not of type 'object'"},
	{schema: "price_table", label: "g_null", data: "null",
		expect: "price_table validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "price_table validation failed at <root>: None is not of type 'object'"},
	{schema: "price_table", label: "g_obj", data: "{}",
		expect: "price_table validation failed at <root>: 'campaign_id' is a required property (+2 more errors)", expect3: "price_table validation failed at <root>: 'campaign_id' is a required property\n  also at <root>: 'updated_at' is a required property\n  also at <root>: 'prices' is a required property"},
	{schema: "price_table", label: "g_str", data: "\"str\"",
		expect: "price_table validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "price_table validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "price_table", label: "g_true", data: "true",
		expect: "price_table validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "price_table validation failed at <root>: True is not of type 'object'"},
	{schema: "protocol_model", label: "g_arr", data: "[1]",
		expect: "protocol_model validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "protocol_model validation failed at <root>: [1] is not of type 'object'"},
	{schema: "protocol_model", label: "g_float", data: "3.14",
		expect: "protocol_model validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "protocol_model validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "protocol_model", label: "g_int", data: "42",
		expect: "protocol_model validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "protocol_model validation failed at <root>: 42 is not of type 'object'"},
	{schema: "protocol_model", label: "g_null", data: "null",
		expect: "protocol_model validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "protocol_model validation failed at <root>: None is not of type 'object'"},
	{schema: "protocol_model", label: "g_obj", data: "{}",
		expect: "protocol_model validation failed at <root>: 'protocol_id' is a required property (+5 more errors)", expect3: "protocol_model validation failed at <root>: 'protocol_id' is a required property\n  also at <root>: 'name' is a required property\n  also at <root>: 'contracts' is a required property\n  (+3 more errors)"},
	{schema: "protocol_model", label: "g_str", data: "\"str\"",
		expect: "protocol_model validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "protocol_model validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "protocol_model", label: "g_true", data: "true",
		expect: "protocol_model validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "protocol_model validation failed at <root>: True is not of type 'object'"},
	{schema: "relation", label: "g_arr", data: "[1]",
		expect: "relation validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "relation validation failed at <root>: [1] is not of type 'object'"},
	{schema: "relation", label: "g_float", data: "3.14",
		expect: "relation validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "relation validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "relation", label: "g_int", data: "42",
		expect: "relation validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "relation validation failed at <root>: 42 is not of type 'object'"},
	{schema: "relation", label: "g_null", data: "null",
		expect: "relation validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "relation validation failed at <root>: None is not of type 'object'"},
	{schema: "relation", label: "g_obj", data: "{}",
		expect: "relation validation failed at <root>: 'relation_id' is a required property (+7 more errors)", expect3: "relation validation failed at <root>: 'relation_id' is a required property\n  also at <root>: 'kind' is a required property\n  also at <root>: 'src' is a required property\n  (+5 more errors)"},
	{schema: "relation", label: "g_str", data: "\"str\"",
		expect: "relation validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "relation validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "relation", label: "g_true", data: "true",
		expect: "relation validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "relation validation failed at <root>: True is not of type 'object'"},
	{schema: "sandbox_execution", label: "g_arr", data: "[1]",
		expect: "sandbox_execution validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "sandbox_execution validation failed at <root>: [1] is not of type 'object'"},
	{schema: "sandbox_execution", label: "g_float", data: "3.14",
		expect: "sandbox_execution validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "sandbox_execution validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "sandbox_execution", label: "g_int", data: "42",
		expect: "sandbox_execution validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "sandbox_execution validation failed at <root>: 42 is not of type 'object'"},
	{schema: "sandbox_execution", label: "g_null", data: "null",
		expect: "sandbox_execution validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "sandbox_execution validation failed at <root>: None is not of type 'object'"},
	{schema: "sandbox_execution", label: "g_obj", data: "{}",
		expect: "sandbox_execution validation failed at <root>: 'exec_id' is a required property (+5 more errors)", expect3: "sandbox_execution validation failed at <root>: 'exec_id' is a required property\n  also at <root>: 'campaign_id' is a required property\n  also at <root>: 'profile' is a required property\n  (+3 more errors)"},
	{schema: "sandbox_execution", label: "g_str", data: "\"str\"",
		expect: "sandbox_execution validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "sandbox_execution validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "sandbox_execution", label: "g_true", data: "true",
		expect: "sandbox_execution validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "sandbox_execution validation failed at <root>: True is not of type 'object'"},
	{schema: "sequence_poc", label: "g_arr", data: "[1]",
		expect: "sequence_poc validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "sequence_poc validation failed at <root>: [1] is not of type 'object'"},
	{schema: "sequence_poc", label: "g_float", data: "3.14",
		expect: "sequence_poc validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "sequence_poc validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "sequence_poc", label: "g_int", data: "42",
		expect: "sequence_poc validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "sequence_poc validation failed at <root>: 42 is not of type 'object'"},
	{schema: "sequence_poc", label: "g_null", data: "null",
		expect: "sequence_poc validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "sequence_poc validation failed at <root>: None is not of type 'object'"},
	{schema: "sequence_poc", label: "g_obj", data: "{}",
		expect: "sequence_poc validation failed at <root>: 'spec_id' is a required property (+3 more errors)", expect3: "sequence_poc validation failed at <root>: 'spec_id' is a required property\n  also at <root>: 'finding_id' is a required property\n  also at <root>: 'actors' is a required property\n  (+1 more errors)"},
	{schema: "sequence_poc", label: "g_str", data: "\"str\"",
		expect: "sequence_poc validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "sequence_poc validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "sequence_poc", label: "g_true", data: "true",
		expect: "sequence_poc validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "sequence_poc validation failed at <root>: True is not of type 'object'"},
	{schema: "sequence_result", label: "g_arr", data: "[1]",
		expect: "sequence_result validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "sequence_result validation failed at <root>: [1] is not of type 'object'"},
	{schema: "sequence_result", label: "g_float", data: "3.14",
		expect: "sequence_result validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "sequence_result validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "sequence_result", label: "g_int", data: "42",
		expect: "sequence_result validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "sequence_result validation failed at <root>: 42 is not of type 'object'"},
	{schema: "sequence_result", label: "g_null", data: "null",
		expect: "sequence_result validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "sequence_result validation failed at <root>: None is not of type 'object'"},
	{schema: "sequence_result", label: "g_obj", data: "{}",
		expect: "sequence_result validation failed at <root>: 'spec_hash' is a required property (+4 more errors)", expect3: "sequence_result validation failed at <root>: 'spec_hash' is a required property\n  also at <root>: 'steps' is a required property\n  also at <root>: 'final_assertions' is a required property\n  (+2 more errors)"},
	{schema: "sequence_result", label: "g_str", data: "\"str\"",
		expect: "sequence_result validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "sequence_result validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "sequence_result", label: "g_true", data: "true",
		expect: "sequence_result validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "sequence_result validation failed at <root>: True is not of type 'object'"},
	{schema: "sft_example", label: "g_arr", data: "[1]",
		expect: "sft_example validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "sft_example validation failed at <root>: [1] is not of type 'object'"},
	{schema: "sft_example", label: "g_float", data: "3.14",
		expect: "sft_example validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "sft_example validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "sft_example", label: "g_int", data: "42",
		expect: "sft_example validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "sft_example validation failed at <root>: 42 is not of type 'object'"},
	{schema: "sft_example", label: "g_null", data: "null",
		expect: "sft_example validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "sft_example validation failed at <root>: None is not of type 'object'"},
	{schema: "sft_example", label: "g_obj", data: "{}",
		expect: "sft_example validation failed at <root>: 'id' is a required property (+10 more errors)", expect3: "sft_example validation failed at <root>: 'id' is a required property\n  also at <root>: 'version' is a required property\n  also at <root>: 'source' is a required property\n  (+8 more errors)"},
	{schema: "sft_example", label: "g_str", data: "\"str\"",
		expect: "sft_example validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "sft_example validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "sft_example", label: "g_true", data: "true",
		expect: "sft_example validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "sft_example validation failed at <root>: True is not of type 'object'"},
	{schema: "sft_example", label: "ifthen_ok", data: "{\"id\":\"SFT-0001\",\"status\":\"draft\",\"taxonomy\":null}",
		expect: "sft_example validation failed at <root>: 'version' is a required property (+7 more errors)", expect3: "sft_example validation failed at <root>: 'version' is a required property\n  also at <root>: 'source' is a required property\n  also at <root>: 'rejection_reasons' is a required property\n  (+5 more errors)"},
	{schema: "sft_example", label: "ifthen_violation", data: "{\"id\":\"SFT-0001\",\"status\":\"draft\",\"taxonomy\":\"bogus-taxonomy\"}",
		expect: "sft_example validation failed at <root>: 'version' is a required property (+9 more errors)", expect3: "sft_example validation failed at <root>: 'version' is a required property\n  also at <root>: 'source' is a required property\n  also at <root>: 'rejection_reasons' is a required property\n  (+7 more errors)"},
	{schema: "shared_memory_row", label: "g_arr", data: "[1]",
		expect: "shared_memory_row validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "shared_memory_row validation failed at <root>: [1] is not of type 'object'"},
	{schema: "shared_memory_row", label: "g_float", data: "3.14",
		expect: "shared_memory_row validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "shared_memory_row validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "shared_memory_row", label: "g_int", data: "42",
		expect: "shared_memory_row validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "shared_memory_row validation failed at <root>: 42 is not of type 'object'"},
	{schema: "shared_memory_row", label: "g_null", data: "null",
		expect: "shared_memory_row validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "shared_memory_row validation failed at <root>: None is not of type 'object'"},
	{schema: "shared_memory_row", label: "g_obj", data: "{}",
		expect: "shared_memory_row validation failed at <root>: 'program_key' is a required property (+2 more errors)", expect3: "shared_memory_row validation failed at <root>: 'program_key' is a required property\n  also at <root>: 'published_at' is a required property\n  also at <root>: 'row' is a required property"},
	{schema: "shared_memory_row", label: "g_str", data: "\"str\"",
		expect: "shared_memory_row validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "shared_memory_row validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "shared_memory_row", label: "g_true", data: "true",
		expect: "shared_memory_row validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "shared_memory_row validation failed at <root>: True is not of type 'object'"},
	{schema: "shared_signature", label: "g_arr", data: "[1]",
		expect: "shared_signature validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "shared_signature validation failed at <root>: [1] is not of type 'object'"},
	{schema: "shared_signature", label: "g_float", data: "3.14",
		expect: "shared_signature validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "shared_signature validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "shared_signature", label: "g_int", data: "42",
		expect: "shared_signature validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "shared_signature validation failed at <root>: 42 is not of type 'object'"},
	{schema: "shared_signature", label: "g_null", data: "null",
		expect: "shared_signature validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "shared_signature validation failed at <root>: None is not of type 'object'"},
	{schema: "shared_signature", label: "g_obj", data: "{}",
		expect: "shared_signature validation failed at <root>: 'signature_id' is a required property (+10 more errors)", expect3: "shared_signature validation failed at <root>: 'signature_id' is a required property\n  also at <root>: 'program_key' is a required property\n  also at <root>: 'program' is a required property\n  (+8 more errors)"},
	{schema: "shared_signature", label: "g_str", data: "\"str\"",
		expect: "shared_signature validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "shared_signature validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "shared_signature", label: "g_true", data: "true",
		expect: "shared_signature validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "shared_signature validation failed at <root>: True is not of type 'object'"},
	{schema: "snapshot", label: "g_arr", data: "[1]",
		expect: "snapshot validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "snapshot validation failed at <root>: [1] is not of type 'object'"},
	{schema: "snapshot", label: "g_float", data: "3.14",
		expect: "snapshot validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "snapshot validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "snapshot", label: "g_int", data: "42",
		expect: "snapshot validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "snapshot validation failed at <root>: 42 is not of type 'object'"},
	{schema: "snapshot", label: "g_null", data: "null",
		expect: "snapshot validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "snapshot validation failed at <root>: None is not of type 'object'"},
	{schema: "snapshot", label: "g_obj", data: "{}",
		expect: "snapshot validation failed at <root>: 'snapshot_id' is a required property (+3 more errors)", expect3: "snapshot validation failed at <root>: 'snapshot_id' is a required property\n  also at <root>: 'campaign_id' is a required property\n  also at <root>: 'created_at' is a required property\n  (+1 more errors)"},
	{schema: "snapshot", label: "g_str", data: "\"str\"",
		expect: "snapshot validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "snapshot validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "snapshot", label: "g_true", data: "true",
		expect: "snapshot validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "snapshot validation failed at <root>: True is not of type 'object'"},
	{schema: "structural_index", label: "g_arr", data: "[1]",
		expect: "structural_index validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "structural_index validation failed at <root>: [1] is not of type 'object'"},
	{schema: "structural_index", label: "g_float", data: "3.14",
		expect: "structural_index validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "structural_index validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "structural_index", label: "g_int", data: "42",
		expect: "structural_index validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "structural_index validation failed at <root>: 42 is not of type 'object'"},
	{schema: "structural_index", label: "g_null", data: "null",
		expect: "structural_index validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "structural_index validation failed at <root>: None is not of type 'object'"},
	{schema: "structural_index", label: "g_obj", data: "{}",
		expect: "structural_index validation failed at <root>: 'campaign_id' is a required property (+3 more errors)", expect3: "structural_index validation failed at <root>: 'campaign_id' is a required property\n  also at <root>: 'snapshot_id' is a required property\n  also at <root>: 'backend' is a required property\n  (+1 more errors)"},
	{schema: "structural_index", label: "g_str", data: "\"str\"",
		expect: "structural_index validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "structural_index validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "structural_index", label: "g_true", data: "true",
		expect: "structural_index validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "structural_index validation failed at <root>: True is not of type 'object'"},
	{schema: "trajectory", label: "g_arr", data: "[1]",
		expect: "", expect3: ""},
	{schema: "trajectory", label: "g_float", data: "3.14",
		expect: "", expect3: ""},
	{schema: "trajectory", label: "g_int", data: "42",
		expect: "", expect3: ""},
	{schema: "trajectory", label: "g_null", data: "null",
		expect: "", expect3: ""},
	{schema: "trajectory", label: "g_obj", data: "{}",
		expect: "", expect3: ""},
	{schema: "trajectory", label: "g_str", data: "\"str\"",
		expect: "", expect3: ""},
	{schema: "trajectory", label: "g_true", data: "true",
		expect: "", expect3: ""},
	{schema: "variant_ladder", label: "g_arr", data: "[1]",
		expect: "variant_ladder validation failed at <root>: [1] is not of type 'object' (+0 more errors)", expect3: "variant_ladder validation failed at <root>: [1] is not of type 'object'"},
	{schema: "variant_ladder", label: "g_float", data: "3.14",
		expect: "variant_ladder validation failed at <root>: 3.14 is not of type 'object' (+0 more errors)", expect3: "variant_ladder validation failed at <root>: 3.14 is not of type 'object'"},
	{schema: "variant_ladder", label: "g_int", data: "42",
		expect: "variant_ladder validation failed at <root>: 42 is not of type 'object' (+0 more errors)", expect3: "variant_ladder validation failed at <root>: 42 is not of type 'object'"},
	{schema: "variant_ladder", label: "g_null", data: "null",
		expect: "variant_ladder validation failed at <root>: None is not of type 'object' (+0 more errors)", expect3: "variant_ladder validation failed at <root>: None is not of type 'object'"},
	{schema: "variant_ladder", label: "g_obj", data: "{}",
		expect: "variant_ladder validation failed at <root>: 'ladder_id' is a required property (+6 more errors)", expect3: "variant_ladder validation failed at <root>: 'ladder_id' is a required property\n  also at <root>: 'finding_id' is a required property\n  also at <root>: 'campaign_id' is a required property\n  (+4 more errors)"},
	{schema: "variant_ladder", label: "g_str", data: "\"str\"",
		expect: "variant_ladder validation failed at <root>: 'str' is not of type 'object' (+0 more errors)", expect3: "variant_ladder validation failed at <root>: 'str' is not of type 'object'"},
	{schema: "variant_ladder", label: "g_true", data: "true",
		expect: "variant_ladder validation failed at <root>: True is not of type 'object' (+0 more errors)", expect3: "variant_ladder validation failed at <root>: True is not of type 'object'"},
}

func TestGoldenOQ3(t *testing.T) {
	for _, g := range goldenRows {
		t.Run(g.schema+"/"+g.label, func(t *testing.T) {
			v, err := ParseOrdered([]byte(g.data))
			if err != nil {
				t.Fatalf("fixture parse: %v", err)
			}
			if err := Validate(v, g.schema, 1); err == nil {
				if g.expect != "" {
					t.Fatalf("expected error %q, got nil", g.expect)
				}
				return
			} else {
				var se *SchemaError
				if !errors.As(err, &se) {
					t.Fatalf("expected *SchemaError, got %T %q", err, err)
				}
				if se.Msg != g.expect {
					t.Errorf("error text mismatch:\n got %q\nwant %q", se.Msg, g.expect)
				}
			}
			if g.expect3 != "" {
				err3 := Validate(v, g.schema, 3)
				var se3 *SchemaError
				if !errors.As(err3, &se3) {
					t.Fatalf("max_errors=3: expected *SchemaError, got %v", err3)
				}
				if se3.Msg != g.expect3 {
					t.Errorf("max_errors=3 text mismatch:\n got %q\nwant %q", se3.Msg, g.expect3)
				}
			}
		})
	}
}
