package capabilities

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"websec/internal/validation"
)

// ---- fixtures ------------------------------------------------------------

// finding builds a minimal finding Value with the given capabilities.
func finding(granted, required []string) validation.Value {
	return validation.VObj(kv("capabilities", validation.VObj(
		kv("granted", strArr(granted)),
		kv("required", strArr(required)),
	)))
}

// strSlice reads a JSON array Value back into []string.
func strSlice(v validation.Value) []string {
	out := make([]string, 0, len(v.A))
	for _, e := range v.A {
		out = append(out, e.S)
	}
	return out
}

// equalStrings is the ordered list comparison.
func equalStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// contains is the membership check.
func contains(items []string, want string) bool {
	for _, it := range items {
		if it == want {
			return true
		}
	}
	return false
}

// loadVectors decodes a committed vector table (generated by the Python twin).
func loadVectors(t *testing.T, name string, out any) {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "vectors", name))
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(raw, out); err != nil {
		t.Fatal(err)
	}
}

// ---- tests/test_capabilities.py ------------------------------------------

func TestNormalizeLabelCollapsesEverySpelling(t *testing.T) {
	variants := []string{"Control Perceived Asset Price",
		"control-perceived  asset_price",
		"  control perceived asset price ",
		"control_perceived_asset_price"}
	seen := map[string]struct{}{}
	for _, v := range variants {
		got := NormalizeLabel(v)
		if got != "control_perceived_asset_price" {
			t.Errorf("NormalizeLabel(%q) = %q, want control_perceived_asset_price",
				v, got)
		}
		seen[got] = struct{}{}
	}
	if len(seen) != 1 {
		t.Errorf("normalized variants collapsed to %d keys, want 1", len(seen))
	}
}

func TestKindOfUsesTheTaxonomyAndAdmitsFreeText(t *testing.T) {
	cases := []struct {
		label, want string
	}{
		{"hold_governor", "authority"},
		{"Hold-Governor", "authority"}, // normalized first
		{"move spot price", "market"},
	}
	for _, c := range cases {
		got, ok := KindOf(c.label)
		if !ok || got != c.want {
			t.Errorf("KindOf(%q) = %q, %v; want %q, true", c.label, got, ok, c.want)
		}
	}
	if got, ok := KindOf("whatever the model invented"); ok {
		t.Errorf("free text classified as %q; want unknown", got)
	}
}

func TestCapabilityDeltaSeparatesGainedFromRequired(t *testing.T) {
	f := finding([]string{"move spot price", "extract protocol liquidity"},
		[]string{"Move-  Spot Price"})
	d := CapabilityDelta(f)
	if got := strSlice(objAt(d, "retained")); !equalStrings(got, []string{"move_spot_price"}) {
		t.Errorf("retained = %v, want [move_spot_price]", got)
	}
	if got := strSlice(objAt(d, "gained")); !equalStrings(got, []string{"extract_protocol_liquidity"}) {
		t.Errorf("gained = %v, want [extract_protocol_liquidity]", got)
	}
	if got := strSlice(objAt(d, "required")); !equalStrings(got, []string{"move_spot_price"}) {
		t.Errorf("required = %v, want [move_spot_price]", got)
	}
	kinds := strSlice(objAt(d, "kinds"))
	if !contains(kinds, "market") || !contains(kinds, "asset") {
		t.Errorf("kinds = %v, want market and asset", kinds)
	}
}

func TestRequiredFallsBackToPreconditions(t *testing.T) {
	// Older findings record prose preconditions, not capability lists. The
	// fallback is best-effort and visible as such in `unclassified`.
	f := validation.VObj(kv("preconditions",
		strArr([]string{"attacker must hold pauser role"})))
	if got := Required(f); !equalStrings(got, []string{"attacker_must_hold_pauser_role"}) {
		t.Errorf("required = %v, want [attacker_must_hold_pauser_role]", got)
	}
	if got, ok := KindOf("attacker must hold pauser role"); ok {
		t.Errorf("prose precondition classified as %q; want unknown", got)
	}
}

func TestNormalizeLabelsDedupesAndSorts(t *testing.T) {
	got := NormalizeLabels([]string{"b cap", "A-CAP", "a cap", "", "  "})
	if !equalStrings(got, []string{"a_cap", "b_cap"}) {
		t.Errorf("NormalizeLabels = %v, want [a_cap b_cap]", got)
	}
	if got := NormalizeLabels(nil); len(got) != 0 {
		t.Errorf("NormalizeLabels(nil) = %v, want empty", got)
	}
}

// ---- tests/test_cap_role_labels.py ---------------------------------------

func TestRoleLabelNormalization(t *testing.T) {
	cases := map[string]string{
		"owner":                  "role_owner",
		"guardian-v2":            "role_guardian_v2",
		"Owner":                  "role_owner",
		"  timelock_controller ": "role_timelock_controller",
	}
	for role, want := range cases {
		if got := RoleLabel(role); got != want {
			t.Errorf("RoleLabel(%q) = %q, want %q", role, got, want)
		}
	}
	if got := RoleLabel(""); got != "role" {
		t.Errorf("RoleLabel(\"\") = %q, want role", got)
	}
}

func TestIsRoleLabel(t *testing.T) {
	for _, label := range []string{"role_owner", "Role-Guardian"} {
		if !IsRoleLabel(label) {
			t.Errorf("IsRoleLabel(%q) = false, want true", label)
		}
	}
	for _, label := range []string{"role", "role_", "roleplay",
		"call_any_entry_point", ""} {
		if IsRoleLabel(label) {
			t.Errorf("IsRoleLabel(%q) = true, want false", label)
		}
	}
}

func TestRoleFromLabelRoundtrip(t *testing.T) {
	for _, r := range []string{"owner", "guardian-v2", "GOvernor",
		"timelock controller"} {
		got, ok := RoleFromLabel(RoleLabel(r))
		if !ok || got != NormalizeLabel(r) {
			t.Errorf("RoleFromLabel(RoleLabel(%q)) = %q, %v; want %q, true",
				r, got, ok, NormalizeLabel(r))
		}
	}
	for _, label := range []string{"roleplay", "role_"} {
		if got, ok := RoleFromLabel(label); ok {
			t.Errorf("RoleFromLabel(%q) = %q, true; want not a role", label, got)
		}
	}
}

func TestKindOfClassifiesRoleLabelsAsAuthority(t *testing.T) {
	for _, label := range []string{"role_owner", "Role-Guardian"} {
		if got, ok := KindOf(label); !ok || got != "authority" {
			t.Errorf("KindOf(%q) = %q, %v; want authority, true", label, got, ok)
		}
	}
	// existing vocabulary untouched
	if got, ok := KindOf("call_any_entry_point"); !ok || got != "authority" {
		t.Errorf("call_any_entry_point kind = %q, %v; want authority", got, ok)
	}
	if got, ok := KindOf("drain_treasury"); !ok || got != "asset" {
		t.Errorf("drain_treasury kind = %q, %v; want asset", got, ok)
	}
	if got, ok := KindOf("something_new"); ok {
		t.Errorf("something_new kind = %q; want unknown", got)
	}
}

// ---- byte-exact vectors --------------------------------------------------

type capabilityVector struct {
	Value      string  `json:"value"`
	Normalized string  `json:"normalized"`
	Kind       *string `json:"kind"`
	IsRole     bool    `json:"is_role"`
	Role       *string `json:"role"`
	Terminal   bool    `json:"terminal"`
}

func TestCapabilityLabelVectors(t *testing.T) {
	var vectors []capabilityVector
	loadVectors(t, "capabilities.json", &vectors)
	if len(vectors) < 25 {
		t.Fatalf("vector table too small: %d", len(vectors))
	}
	for _, v := range vectors {
		if got := NormalizeLabel(v.Value); got != v.Normalized {
			t.Errorf("NormalizeLabel(%q) = %q, want %q", v.Value, got, v.Normalized)
		}
		kind, ok := KindOf(v.Value)
		if (v.Kind != nil) != ok || (ok && kind != *v.Kind) {
			t.Errorf("KindOf(%q) = %q, %v; want %v", v.Value, kind, ok, v.Kind)
		}
		if got := IsRoleLabel(v.Value); got != v.IsRole {
			t.Errorf("IsRoleLabel(%q) = %v, want %v", v.Value, got, v.IsRole)
		}
		role, roleOK := RoleFromLabel(v.Value)
		if (v.Role != nil) != roleOK || (roleOK && role != *v.Role) {
			t.Errorf("RoleFromLabel(%q) = %q, %v; want %v", v.Value, role, roleOK, v.Role)
		}
		if got := IsTerminal(v.Value); got != v.Terminal {
			t.Errorf("IsTerminal(%q) = %v, want %v", v.Value, got, v.Terminal)
		}
	}
}

type deltaVector struct {
	Finding      json.RawMessage `json:"finding"`
	GrantedJSON  string          `json:"granted_json"`
	RequiredJSON string          `json:"required_json"`
	DeltaJSON    string          `json:"delta_json"`
}

func TestCapabilityDeltaVectors(t *testing.T) {
	var vectors []deltaVector
	loadVectors(t, "capability_delta.json", &vectors)
	if len(vectors) < 6 {
		t.Fatalf("vector table too small: %d", len(vectors))
	}
	for i, v := range vectors {
		f, err := validation.ParseOrdered(v.Finding)
		if err != nil {
			t.Fatalf("vector %d: %v", i, err)
		}
		if got := validation.CanonCompact(strArr(Granted(f))); got != v.GrantedJSON {
			t.Errorf("vector %d granted = %s, want %s", i, got, v.GrantedJSON)
		}
		if got := validation.CanonCompact(strArr(Required(f))); got != v.RequiredJSON {
			t.Errorf("vector %d required = %s, want %s", i, got, v.RequiredJSON)
		}
		if got := validation.CanonCompact(CapabilityDelta(f)); got != v.DeltaJSON {
			t.Errorf("vector %d delta = %s, want %s", i, got, v.DeltaJSON)
		}
	}
}
