package assets

// TestAssetPackManifest pins the byte content of every embedded asset pack
// against the committed SHA-256 manifest (testdata/asset_manifest.json,
// regenerated by scripts/sync-asset-manifest.py).
//
// This is the successor of the twin-retirement-era byte-identity tests that
// compared the asset packs against the web3sec-final checkout and silently
// skipped when it was absent: the manifest pins the SAME bytes with zero
// external dependencies, and a stale manifest fails the gate instead of
// skipping past it. An intentional asset edit must ship with a regenerated
// manifest — that diff is the review surface for "did you mean to change a
// shipped prompt/schema/playbook?".

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"io/fs"
	"os"
	"strings"
	"testing"
)

type packEntry struct {
	SHA256 string `json:"sha256"`
	Size   int64  `json:"size"`
}

type assetManifest struct {
	Version int                         `json:"version"`
	Packs   map[string]map[string]packEntry `json:"packs"`
}

func readManifest(t *testing.T) assetManifest {
	t.Helper()
	// testdata/ is excluded from go:embed by definition; the test binary
	// runs in the package directory, so a plain read is the manifest.
	raw, err := os.ReadFile("testdata/asset_manifest.json")
	if err != nil {
		t.Fatalf("manifest missing (run python3 scripts/sync-asset-manifest.py): %v", err)
	}
	var m assetManifest
	if err := json.Unmarshal(raw, &m); err != nil {
		t.Fatalf("manifest unreadable: %v", err)
	}
	if m.Version != 1 {
		t.Fatalf("manifest version = %d, want 1", m.Version)
	}
	return m
}

// TestAssetPackManifest: for each pack, the embedded file set must equal the
// manifest key set, and each embedded file must hash + size-match.
func TestAssetPackManifest(t *testing.T) {
	m := readManifest(t)
	packs := map[string]struct {
		fs   fs.FS
		root string
	}{
		"schema":         {FS, "schema"},
		"archetypes":     {ArchetypesFS, "archetypes"},
		"playbooks":      {PlaybooksFS, "playbooks"},
		"prompts":        {PromptsFS, "prompts"},
		"prompts_legacy": {LegacyPromptsFS, "prompts_legacy"},
		"runbook":        {RunbookFS, "runbook"},
	}
	for name, pack := range packs {
		want, ok := m.Packs[name]
		if !ok {
			t.Fatalf("pack %q missing from the manifest", name)
		}
		var seen []string
		err := fs.WalkDir(pack.fs, pack.root, func(p string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() {
				return nil
			}
			rel := strings.TrimPrefix(p, pack.root+"/")
			seen = append(seen, rel)
			data, err := fs.ReadFile(pack.fs, p)
			if err != nil {
				return err
			}
			e, ok := want[rel]
			if !ok {
				t.Errorf("%s/%s: embedded but not in the manifest (asset added without regenerating it?)", name, rel)
				return nil
			}
			sum := sha256.Sum256(data)
			if got := hex.EncodeToString(sum[:]); got != e.SHA256 {
				t.Errorf("%s/%s: sha256 %s != manifest %s (asset edited without regenerating the manifest)", name, rel, got, e.SHA256)
			}
			if int64(len(data)) != e.Size {
				t.Errorf("%s/%s: size %d != manifest %d", name, rel, len(data), e.Size)
			}
			return nil
		})
		if err != nil {
			t.Fatalf("walk %s: %v", name, err)
		}
		inSet := map[string]bool{}
		for _, s := range seen {
			inSet[s] = true
		}
		for rel := range want {
			if !inSet[rel] {
				t.Errorf("%s/%s: in the manifest but not embedded (asset removed without regenerating it?)", name, rel)
			}
		}
	}
}
